FROM python:3.10

WORKDIR /opt/flower

ENV PYTHONUNBUFFERED 1

COPY requirements.txt requirements.txt

RUN  pip install --upgrade pip \
     && pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod a+x ./bash/start_flower.sh
ENTRYPOINT ["./bash/start_flower.sh"]