@startuml notify_pipeline_code_level
autonumber

database dead_queue as "Dead Letter Queue"
database queue as "Queue"
participant consumer as "Consumer"
participant resolver as "Resolver"

participant user_provider as "User provider"
database user_db as "User db"

participant notify_sender as "Notify sender"
participant notify_provider as "Notify provider"

actor customer as "Customer"

consumer -> queue: Get notify request

consumer -> resolver

resolver -> user_provider

user_provider -> user_db: Read user info

resolver -> notify_sender

notify_sender -> notify_provider

notify_provider -> customer

notify_provider -> notify_sender: Result: True or False

alt Send error
    notify_sender -> dead_queue
    dead_queue -> queue
end


@enduml