@startuml notification
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define SPRITES https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.0/sprites
!include SPRITES/postgresql.puml
!include SPRITES/rabbitmq.puml

HIDE_STEREOTYPE()

Person(user, "Customer")
Person(admin, "Admin")

System(external, "External service")

Container(admin_panel, "Admin Panel")
Container(notify_api, "Notify API")
Container(notify_service, "Notify Service")
ContainerDb(db, "Notify DB", "PostgreSQL", $sprite="postgresql")
ContainerDb(query, "Task query", "RabbitMQ", $sprite="rabbitmq")
Container(worker, "Worker")

Rel(external, notify_api, "")
Rel(notify_api, query, "Put in query")

Rel(admin_panel, db, "")
Rel(admin, admin_panel, "")

Rel_L(notify_service, db, "Read")
Rel(notify_service, worker, "Send notify task")
Rel_R(notify_service, query, "Pop")

Rel(worker, user, "Notify")

@enduml