@startuml notification
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define SPRITES https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.0/sprites
!include SPRITES/postgresql.puml
!include SPRITES/rabbitmq.puml

HIDE_STEREOTYPE()

Person(user, "Customer")
Person(notify_admin, "Admin")
System(external, "Auth service")

Container(admin_panel, "Admin Panel")
Container(notify_api, "Notify API")
Container(regular_converter, "Regular converter service")
Container(notify_service, "Notify Service")
ContainerDb(db, "Notify DB", "PostgreSQL", $sprite="postgresql")
ContainerDb(query, "Task queue", "RabbitMQ", $sprite="rabbitmq")
ContainerDb(user_db, "User database", "PostgreSQL", $sprite="postgresql")
Container(worker, "Worker")

Rel(notify_admin, admin_panel, "")
Rel(admin_panel, db, "")

Rel(external, notify_api, "")
Rel(notify_api, query, "Put in query")

Rel(regular_converter, db, "Read")
Rel(regular_converter, notify_api, "")
Rel(notify_service, worker, "Notify task")
Rel(notify_service, user_db, "Get users")
Rel(notify_service, query, "Pop")

Rel(worker, user, "Notify")

@enduml