@startuml sequence
autonumber

participant external as "Regular notify converter"
participant api as "Notify API"
database query as "Queue"
database db as "Notify DB"
participant service as "Notify Service"
participant worker as "Worker"

actor customer as "Customer"

external -> api: HTTP POST: Instant notify
api -> query: Put notify-request
api -> external: HTTP 202: Accepted

service -> query: Pop notify-requests
query -> service

service -> db: Get notify-templates
db -> service

service -> worker: Send notify-task
worker -> customer: Notify

@enduml