@startuml to_be
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define SPRITES https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.0/sprites
!include SPRITES/postgresql.puml
!include SPRITES/rabbitmq.puml
' skinparam linetype polyline
skinparam linetype ortho

HIDE_STEREOTYPE()

Person(user, "Customer")
Person(notify_admin, "Admin")
System(auth_service, "Auth service")

System_Boundary(notification_system, "Notification") {
    Container(admin_panel, "Admin Panel")
    Container(notify_api, "Notify API")
    Container(notify_regular_service, "Regular converter service")
    Container(notify_workers_pipeline, "Notify Workers Pipeline")
    ContainerDb(db, "Notify DB", "PostgreSQL", $sprite="postgresql")

    ContainerDb(queue, "Task queue", "RabbitMQ", $sprite="rabbitmq")
    ContainerDb(user_db, "User database", "PostgreSQL", $sprite="postgresql")
}

Rel(auth_service, notify_api, "")

Rel(notify_admin, admin_panel, "")
Rel(admin_panel, db, "")

Rel_R(notify_api, db, "")
Rel(notify_api, queue, " ")

Rel(notify_regular_service, db, " ")
Rel(notify_regular_service, notify_api, "")

Rel(notify_workers_pipeline, user_db, " ")
Rel_R(queue, notify_workers_pipeline, " ")
Rel(notify_workers_pipeline, db, " ")

Rel(notify_workers_pipeline, user, "Notify")

@enduml